name: Bleeding-Edge Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tag:
    name: Generate version tag from workflow SHA
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.parse.outputs.tag }}
    steps:
      - name: Parse SHA
        id: parse
        run: echo "TAG=main_$(cut -c 1-7 <<< '${{ github.workflow_sha }}')" >> "$GITHUB_OUTPUT"

  test_gofmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.1'

      - name: Execute gofmt
        run: output=$(gofmt -l -e .); echo "$output"; test "$output" = ''

  build:
    runs-on: ubuntu-latest
    needs:
      - tag
      - test_gofmt
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25.1'

    - name: Set version to workflow SHA
      run: sed -i 's/Indigo CIL, v0\.0\.0/Indigo CIL, workflow ${{ needs.tag.outputs.tag }}/' ./cmd/indigo/main.go

    - name: Build server
      run: go build -v ./cmd/indigo

    - name: Build API documentation
      run: npx @redocly/cli@latest build-docs ./api/v1.json

    - uses: actions/upload-artifact@v4
      name: Upload server binary
      with:
        path: 'indigo'
        name: 'indigo'

    - uses: actions/upload-artifact@v4
      name: Upload API documentation
      with:
        path: 'redoc-static.html'
        name: 'redoc-static.html'

  test_unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.1'

  test_documentation:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v6.1.0

      - uses: actions/download-artifact@v4
        name: Download server artifact
        with:
          name: "indigo"

      - name: Set server executable
        run: chmod +x indigo

      - name: Install example env
        run: cp .env.example .env

      - name: Test route documentation
        env: 
          INDIGO_BACKEND_EXECUTABLE_LOCATION: "./indigo"
          OPENAPI_SPEC_LOCATION: "./api/v1.json"
        run: python3 ./ci/routing_documentation.py -v

  deploy:
    runs-on: self-hosted
    needs: [build, test_documentation, test_unit]
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/download-artifact@v4
        name: Download server artifact
        with:
          name: "indigo"

      - uses: actions/download-artifact@v4
        name: Download API documentation artifact
        with:
          name: "redoc-static.html"

      - name: Install server
        run: install -m 775 indigo /stack/bin/

      - name: Install API documentation
        run: install -m 775 redoc-static.html /stack/www/api/

      - name: Restart bleeding container
        run: docker compose --project-directory /stack restart bleeding

